import type { Metadata } from "next";
import React, { Suspense } from "react";
import "./globals.css";
import Loading from "@/components/loading";
import { Toaster } from "@/components/ui/toaster";
import { getUserInfo } from "@/lib/auth";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Trang Chủ",
  description: "Generated by create next app",
};

export default async function UserLayout({
  admin,
  student,
  teacher,
  children,
}: {
  admin: React.ReactNode;
  children: React.ReactNode;
  student: React.ReactNode;
  teacher: React.ReactNode;
}) {
  const cookieStore = cookies();
  const role = cookieStore.get("ID")?.value;
  const token = cookieStore.get("token")?.value;
  const result = await getUserInfo(token, role);
  const user_role =
    result &&
    typeof result === "object" &&
    result !== null &&
    "result" in result
      ? (result.result as { role: string }).role
      : undefined;
  return (
    <Suspense fallback={<Loading />}>
      <section>
        {user_role == "1"
          ? admin
          : user_role == "2"
          ? teacher
          : user_role == "3"
          ? student
          : children}
        <Toaster />
      </section>
    </Suspense>
  );
}
