INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (1, 1, 'Huyện Si Ma Cai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (2, 1, 'Huyện Mường Khương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (3, 1, 'Huyện Bảo Thắng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (4, 1, 'Huyện Văn Bàn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (5, 1, 'Thị xã Sa Pa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (6, 1, 'Huyện Bắc Hà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (7, 1, 'Huyện Bảo Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (8, 1, 'Huyện Bát Xát');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (9, 1, 'Thành phố Lào Cai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (10, 2, 'Quận Đặc Biệt');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (11, 2, 'Huyện Phù Cừ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (12, 2, 'Huyện Văn Lâm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (13, 2, 'Huyện Văn Giang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (14, 2, 'Huyện Tiên Lữ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (15, 2, 'Huyện Yên Mỹ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (16, 2, 'Thị xã Mỹ Hào');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (17, 2, 'Huyện Khoái Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (18, 2, 'Huyện Ân Thi');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (19, 2, 'Huyện Kim Động');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (20, 2, 'Thành phố Hưng Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (21, 3, 'Huyện Yên Thủy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (22, 3, 'Huyện Mai Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (23, 3, 'Huyện Lạc Thủy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (24, 3, 'Huyện Lạc Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (25, 3, 'Huyện Kim Bôi');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (26, 3, 'Huyện Cao Phong');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (27, 3, 'Huyện Tân Lạc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (28, 3, 'Huyện Lương Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (29, 3, 'Huyện Kỳ Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (30, 3, 'Huyện Đà Bắc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (31, 3, 'Thành phố Hòa Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (32, 4, 'huyện Sốp Cộp');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (33, 4, 'Huyện Mường La');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (34, 4, 'Huyện Yên Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (35, 4, 'Huyện Vân Hồ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (36, 4, 'Huyện Quỳnh Nhai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (37, 4, 'Huyện Bắc Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (38, 4, 'Huyện Thuận Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (39, 4, 'Huyện Sông Mã');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (40, 4, 'Huyện Phù Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (41, 4, 'Huyện Mộc Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (42, 4, 'Huyện Mai Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (43, 4, 'Thành phố Sơn La');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (44, 5, 'Huyện Nậm Pồ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (45, 5, 'Huyện Mường Ảng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (46, 5, 'Huyện Điện Biên Đông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (47, 5, 'Thị xã Mường Lay');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (48, 5, 'Huyện Tuần Giáo');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (49, 5, 'Huyện Tủa Chùa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (50, 5, 'Huyện Mường Nhé');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (51, 5, 'Huyện Mường Chà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (52, 5, 'Huyện Điện Biên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (53, 5, 'Thành phố Điện Biên Phủ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (54, 6, 'Huyện Than Uyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (55, 6, 'Huyện Tân Uyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (56, 6, 'Huyện Tam Đường');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (57, 6, 'Huyện Sìn Hồ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (58, 6, 'Huyện Phong Thổ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (59, 6, 'Huyện Nậm Nhùn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (60, 6, 'Huyện Mường Tè');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (61, 6, 'Thành phố Lai Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (62, 7, 'Huyện Yên Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (63, 7, 'Huyện Trạm Tấu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (64, 7, 'Thị xã Nghĩa Lộ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (65, 7, 'Huyện Văn Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (66, 7, 'Huyện Văn Chấn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (67, 7, 'Huyện Trấn Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (68, 7, 'Huyện Mù Cang Chải');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (69, 7, 'Huyện Lục Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (70, 7, 'Thành phố Yên Bái');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (71, 8, 'Huyện Vân Canh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (72, 8, 'Huyện Tây Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (73, 8, 'Huyện Phù Mỹ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (74, 8, 'Huyện Vĩnh Thạnh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (75, 8, 'Huyện Hoài Ân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (76, 8, 'Huyện Tuy Phước');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (77, 8, 'Huyện An Lão');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (78, 8, 'Thị xã Hoài Nhơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (79, 8, 'Huyện Phù Cát');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (80, 8, 'Thị xã An Nhơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (81, 8, 'Thành phố Quy Nhơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (82, 9, 'Huyện Thuận Nam');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (83, 9, 'Huyện Thuận Bắc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (84, 9, 'Huyện Bác Ái');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (85, 9, 'Huyện Ninh Phước');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (86, 9, 'Huyện Ninh Hải');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (87, 9, 'Huyện Ninh Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (88, 9, 'Thành phố Phan Rang – Tháp Chàm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (89, 10, 'Huyện Tuy An');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (90, 10, 'Huyện Tây Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (91, 10, 'Huyện Đồng Xuân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (92, 10, 'Thị xã Đông Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (93, 10, 'Huyện Sơn Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (94, 10, 'Huyện Sông Hinh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (95, 10, 'Huyện Phú Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (96, 10, 'Thị Xã Sông Cầu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (97, 10, 'Thành phố Tuy Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (98, 11, 'Huyện Ia H Drai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (99, 11, 'Huyện Tu Mơ Rông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (100, 11, 'Huyện Sa Thầy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (101, 11, 'Huyện Ngọc Hồi');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (102, 11, 'Huyện Kon Rẫy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (103, 11, 'Huyện Đắk Tô');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (104, 11, 'Huyện Đắk Glei');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (105, 11, 'Huyện Đắk Hà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (106, 11, 'Huyện Kon Plông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (107, 11, 'Thành phố Kon Tum');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (108, 12, 'Huyện Hàm Tân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (109, 12, 'Huyện đảo Phú Quý');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (110, 12, 'Huyện Tánh Linh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (111, 12, 'Huyện Tuy Phong');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (112, 12, 'Huyện Bắc Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (113, 12, 'Huyện Đức Linh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (114, 12, 'Thị xã La Gi');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (115, 12, 'Huyện Hàm Thuận Bắc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (116, 12, 'Huyện Hàm Thuận Nam');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (117, 12, 'Thành phố Phan Thiết');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (118, 13, 'Huyện Vĩnh Lợi');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (119, 13, 'Huyện Phước Long');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (120, 13, 'Huyện Hồng Dân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (121, 13, 'Thị Xã Giá Rai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (122, 13, 'Huyện Đông Hải');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (123, 13, 'Huyện Hòa Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (124, 13, 'Thành phố Bạc Liêu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (125, 14, 'Huyện Ngọc Hiển');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (126, 14, 'Huyện U Minh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (127, 14, 'Huyện Trần Văn Thời');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (128, 14, 'Huyện Đầm Dơi');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (129, 14, 'Huyện Cái Nước');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (130, 14, 'Huyện Phú Tân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (131, 14, 'Huyện Năm Căn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (132, 14, 'Huyện Thới Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (133, 14, 'Thành phố Cà Mau');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (134, 15, 'Huyện Long Mỹ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (135, 15, 'Thị xã Long Mỹ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (136, 15, 'Huyện Châu Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (137, 15, 'Huyện Vị Thuỷ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (138, 15, 'Huyện Châu Thành A');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (139, 15, 'Huyện Phụng Hiệp');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (140, 15, 'Thành phố Ngã Bảy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (141, 15, 'Thành phố Vị Thanh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (142, 16, 'Huyện Lương Tài');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (143, 16, 'Huyện Yên Phong');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (144, 16, 'Thị xã Thuận Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (145, 16, 'Huyện Gia Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (146, 16, 'Thị xã Từ Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (147, 16, 'Huyện Tiên Du');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (148, 16, 'Huyện Quế Võ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (149, 16, 'Thành phố Bắc Ninh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (150, 17, 'Huyện Lục Ngạn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (151, 17, 'Huyện Lục Nam');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (152, 17, 'Huyện Yên Thế');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (153, 17, 'Huyện Yên Dũng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (154, 17, 'Huyện Việt Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (155, 17, 'Huyện Tân Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (156, 17, 'Huyện Sơn Động');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (157, 17, 'Huyện Lạng Giang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (158, 17, 'Huyện Hiệp Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (159, 17, 'Thành phố Bắc Giang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (160, 18, 'Huyện Văn Quan');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (161, 18, 'Huyện Văn Lãng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (162, 18, 'Huyện Đình Lập');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (163, 18, 'Huyện Chi Lăng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (164, 18, 'Huyện Bình Gia');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (165, 18, 'Huyện Bắc Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (166, 18, 'Huyện Tràng Định');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (167, 18, 'Huyện Lộc Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (168, 18, 'Huyện Hữu Lũng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (169, 18, 'Huyện Cao Lộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (170, 18, 'Thành phố Lạng Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (171, 19, 'Huyện Quảng Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (172, 19, 'Huyện Trà Lĩnh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (173, 19, 'Huyện Thông Nông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (174, 19, 'Huyện Thạch An');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (175, 19, 'Huyện Quảng Uyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (176, 19, 'Huyện Nguyên Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (177, 19, 'Huyện Hạ Lang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (178, 19, 'Huyện Bảo Lạc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (179, 19, 'Huyện Trùng Khánh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (180, 19, 'Huyện Phục Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (181, 19, 'Huyện Hòa An');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (182, 19, 'Huyện Hà Quảng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (183, 19, 'Huyện Bảo Lâm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (184, 19, 'Thành phố Cao Bằng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (185, 20, 'Huyện Pác Nặm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (186, 20, 'Huyện Ngân Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (187, 20, 'Huyện Na Rì');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (188, 20, 'Huyện Chợ Mới');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (189, 20, 'Huyện Chợ Đồn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (190, 20, 'Huyện Bạch Thông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (191, 20, 'Huyện Ba Bể');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (192, 20, 'Thành phố Bắc Kạn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (193, 21, 'Huyện Phú Lương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (194, 21, 'Huyện Võ Nhai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (195, 21, 'Huyện Phú Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (196, 21, 'Thị xã Phổ Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (197, 21, 'Huyện Định Hóa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (198, 21, 'Huyện Đại Từ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (199, 21, 'Huyện Đồng Hỷ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (200, 21, 'Thành Phố Sông Công');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (201, 21, 'Thành phố Thái Nguyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (202, 22, 'Huyện Thăng Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (203, 22, 'Huyện Tiên Phước');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (204, 22, 'Huyện Tây Giang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (205, 22, 'Huyện Phước Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (206, 22, 'Huyện Nông Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (207, 22, 'Huyện Nam Trà My');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (208, 22, 'Huyện Nam Giang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (209, 22, 'Huyện Hiệp Đức');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (210, 22, 'Huyện Đông Giang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (211, 22, 'Huyện Bắc Trà My');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (212, 22, 'Huyện Quế Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (213, 22, 'Huyện Phú Ninh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (214, 22, 'Huyện Núi Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (215, 22, 'Huyện Đại Lộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (216, 22, 'Thị xã Điện Bàn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (217, 22, 'Huyện Duy Xuyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (218, 22, 'Thành phố Hội An');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (219, 22, 'Thành phố Tam Kỳ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (220, 23, 'Huyện Trà Bồng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (221, 23, 'Huyện Sơn Tây');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (222, 23, 'Huyện Mộ Đức');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (223, 23, 'Huyện Ba Tơ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (224, 23, 'Huyện Tây Trà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (225, 23, 'Huyện Sơn Hà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (226, 23, 'Huyện Minh Long');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (227, 23, 'Huyện đảo Lý Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (228, 23, 'Huyện Nghĩa Hành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (229, 23, 'Thị xã Đức Phổ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (230, 23, 'Huyện Bình Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (231, 23, 'Huyện Tư Nghĩa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (232, 23, 'Huyện Sơn Tịnh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (233, 23, 'Thành phố Quảng Ngãi');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (234, 24, 'Huyện Cư Jút');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (235, 24, 'Huyện Tuy Đức');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (236, 24, 'Huyện Krông Nô');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (237, 24, 'Huyện Đắk Song');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (238, 24, 'Huyện Đắk Mil');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (239, 24, 'Huyện Đắk Glong');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (240, 24, 'Huyện Đắk R lấp');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (241, 24, 'Thành phố Gia Nghĩa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (242, 25, 'Thị xã Trảng Bàng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (243, 25, 'Huyện Gò Dầu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (244, 25, 'Huyện Bến Cầu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (245, 25, 'Huyện Dương Minh Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (246, 25, 'Huyện Tân Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (247, 25, 'Huyện Tân Biên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (248, 25, 'Thị xã Hòa Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (249, 25, 'Huyện Châu Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (250, 25, 'Thành phố Tây Ninh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (251, 26, 'Huyện Phú Riềng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (252, 26, 'Huyện Bù Gia Mập');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (253, 26, 'Huyện Bù Đốp');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (254, 26, 'Huyện Lộc Ninh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (255, 26, 'Huyện Bù Đăng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (256, 26, 'Thị xã Phước Long');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (257, 26, 'Thị xã Bình Long');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (258, 26, 'Huyện Hớn Quản');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (259, 26, 'Huyện Chơn Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (260, 26, 'Huyện Đồng Phú');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (261, 26, 'Thành phố Đồng Xoài');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (262, 27, 'Huyện Hải Lăng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (263, 27, 'Huyện đảo Cồn Cỏ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (264, 27, 'Huyện Đa Krông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (265, 27, 'Huyện Triệu Phong');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (266, 27, 'Huyện Gio Linh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (267, 27, 'Huyện Cam Lộ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (268, 27, 'Huyện Vĩnh Linh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (269, 27, 'Huyện Hướng Hóa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (270, 27, 'Thị xã Quảng Trị');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (271, 27, 'Thành phố Đông Hà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (272, 28, 'Huyện Tuyên Hóa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (273, 28, 'Huyện Quảng Trạch');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (274, 28, 'Huyện Minh Hóa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (275, 28, 'Huyện Quảng Ninh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (276, 28, 'Thị xã Ba Đồn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (277, 28, 'Huyện Bố Trạch');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (278, 28, 'Huyện Lệ Thủy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (279, 28, 'Thành phố Đồng Hới');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (280, 29, 'Thị xã Kỳ Anh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (281, 29, 'Huyện Vũ Quang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (282, 29, 'Huyện Lộc Hà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (283, 29, 'Huyện Hương Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (284, 29, 'Huyện Đức Thọ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (285, 29, 'Huyện Can Lộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (286, 29, 'Huyện Thạch Hà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (287, 29, 'Huyện Cẩm Xuyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (288, 29, 'Thị xã Hồng Lĩnh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (289, 29, 'Huyện Nghi Xuân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (290, 29, 'Huyện Hương Khê');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (291, 29, 'Huyện Kỳ Anh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (292, 29, 'Thành phố Hà Tĩnh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (293, 30, 'Huyện Thanh Chương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (294, 30, 'Huyện Tương Dương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (295, 30, 'Huyện Quỳ Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (296, 30, 'Huyện Quế Phong');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (297, 30, 'Huyện Nam Đàn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (298, 30, 'Huyện Kỳ Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (299, 30, 'Huyện Hưng Nguyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (300, 30, 'Huyện Nghi Lộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (301, 30, 'Huyện Con Cuông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (302, 30, 'Huyện Quỳ Hợp');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (303, 30, 'Huyện Nghĩa Đàn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (304, 30, 'Thị xã Thái Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (305, 30, 'Thị xã Hoàng Mai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (306, 30, 'Huyện Quỳnh Lưu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (307, 30, 'Huyện Diễn Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (308, 30, 'Huyện Yên Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (309, 30, 'Huyện Tân Kỳ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (310, 30, 'Huyện Anh Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (311, 30, 'Huyện Đô Lương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (312, 30, 'Thị xã Cửa Lò');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (313, 30, 'Thành phố Vinh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (314, 31, 'Huyện Thiệu Hóa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (315, 31, 'Huyện Nga Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (316, 31, 'Huyện Lang Chánh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (317, 31, 'Huyện Cẩm Thủy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (318, 31, 'Huyện Triệu Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (319, 31, 'Huyện Như Thanh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (320, 31, 'Huyện Nông Cống');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (321, 31, 'Huyện Bá Thước');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (322, 31, 'Huyện Quan Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (323, 31, 'Huyện Hậu Lộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (324, 31, 'Huyện Đông Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (325, 31, 'Huyện Vĩnh Lộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (326, 31, 'Huyện Thạch Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (327, 31, 'Huyện Quan Hóa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (328, 31, 'Huyện Mường Lát');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (329, 31, 'Huyện Hà Trung');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (330, 31, 'Thị xã Bỉm Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (331, 31, 'Huyện Yên Định');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (332, 31, 'Huyện Ngọc Lặc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (333, 31, 'Huyện Thọ Xuân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (334, 31, 'Huyện Thường Xuân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (335, 31, 'Huyện Như Xuân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (336, 31, 'Thị Xã Nghi Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (337, 31, 'Huyện Hoằng Hóa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (338, 31, 'Huyện Quảng Xương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (339, 31, 'Thành phố Sầm Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (340, 31, 'Thành phố Thanh Hóa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (341, 32, 'Huyện Yên Mô');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (342, 32, 'Huyện Nho Quan');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (343, 32, 'Huyện Kim Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (344, 32, 'Huyện Gia Viễn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (345, 32, 'Huyện Hoa Lư');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (346, 32, 'Huyện Yên Khánh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (347, 32, 'Thành phố Tam Điệp');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (348, 32, 'Thành phố Ninh Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (349, 33, 'Huyện Thanh Liêm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (350, 33, 'Huyện Lý Nhân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (351, 33, 'Huyện Kim Bảng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (352, 33, 'Huyện Bình Lục');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (353, 33, 'Thị xã Duy Tiên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (354, 33, 'Thành phố Phủ Lý');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (355, 34, 'Huyện Xuân Trường');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (356, 34, 'Huyện Vụ Bản');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (357, 34, 'Huyện Trực Ninh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (358, 34, 'Huyện Nghĩa Hưng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (359, 34, 'Huyện Giao Thủy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (360, 34, 'Huyện Nam Trực');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (361, 34, 'Huyện Mỹ Lộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (362, 34, 'Huyện Ý Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (363, 34, 'Huyện Hải Hậu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (364, 34, 'Thành phố Nam Định');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (365, 35, 'Huyện Hoành Bồ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (366, 35, 'Thị xã Đông Triều');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (367, 35, 'Huyện Đầm Hà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (368, 35, 'Huyện Ba Chẽ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (369, 35, 'Huyện đảo Cô Tô');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (370, 35, 'Thị xã Quảng Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (371, 35, 'Huyện Tiên Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (372, 35, 'Huyện Hải Hà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (373, 35, 'Huyện đảo Vân Đồn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (374, 35, 'Huyện Bình Liêu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (375, 35, 'Thành phố Uông Bí');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (376, 35, 'Thành phố Cẩm Phả');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (377, 35, 'Thành phố Hạ Long');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (378, 35, 'Thành phố Móng Cái');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (379, 36, 'Huyện Thanh Ba');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (380, 36, 'Huyện Tam Nông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (381, 36, 'Huyện Yên Lập');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (382, 36, 'Huyện Thanh Thủy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (383, 36, 'Thị xã Phú Thọ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (384, 36, 'Huyện Thanh Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (385, 36, 'Huyện Tân Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (386, 36, 'Huyện Phù Ninh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (387, 36, 'Huyện Lâm Thao');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (388, 36, 'Huyện Hạ Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (389, 36, 'Huyện Đoan Hùng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (390, 36, 'Huyện Cẩm Khê');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (391, 36, 'Thành phố Việt Trì');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (392, 37, 'Huyện Sơn Dương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (393, 37, 'Huyện Chiêm Hóa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (394, 37, 'Huyện Na Hang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (395, 37, 'Huyện Lâm Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (396, 37, 'Huyện Hàm Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (397, 37, 'Huyện Yên Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (398, 37, 'Thành phố Tuyên Quang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (399, 38, 'Huyện Vị Xuyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (400, 38, 'Huyện Bắc Mê');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (401, 38, 'Huyện Yên Minh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (402, 38, 'Huyện Xín Mần');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (403, 38, 'Huyện Quang Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (404, 38, 'Huyện Quản Bạ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (405, 38, 'Huyện Mèo Vạc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (406, 38, 'Huyện Hoàng Su Phì');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (407, 38, 'Huyện Đồng Văn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (408, 38, 'Huyện Bắc Quang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (409, 38, 'Thành phố Hà Giang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (410, 39, 'Huyện Tiền Hải');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (411, 39, 'Huyện Kiến Xương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (412, 39, 'Huyện Thái Thụy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (413, 39, 'Huyện Quỳnh Phụ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (414, 39, 'Huyện Hưng Hà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (415, 39, 'Huyện Vũ Thư');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (416, 39, 'Huyện Đông Hưng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (417, 39, 'Thành phố Thái Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (418, 40, 'Huyện Thanh Miện');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (419, 40, 'Huyện Thanh Hà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (420, 40, 'Huyện Tứ Kỳ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (421, 40, 'Huyện Ninh Giang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (422, 40, 'Thành phố Chí Linh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (423, 40, 'Huyện Kim Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (424, 40, 'Huyện Gia Lộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (425, 40, 'Thị xã Kinh Môn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (426, 40, 'Huyện Cẩm Giàng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (427, 40, 'Huyện Bình Giang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (428, 40, 'Huyện Nam Sách');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (429, 40, 'Thành phố Hải Dương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (430, 41, 'Huyện Kiến Thụy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (431, 41, 'Huyện đảo Cát Hải');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (432, 41, 'Huyện đảo Bạch Long Vĩ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (433, 41, 'Huyện Vĩnh Bảo');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (434, 41, 'Huyện Tiên Lãng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (435, 41, 'Huyện An Lão');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (436, 41, 'Huyện An Dương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (437, 41, 'Huyện Thủy Nguyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (438, 41, 'Quận Đồ Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (439, 41, 'Quận Dương Kinh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (440, 41, 'Quận Hải An');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (441, 41, 'Quận Kiến An');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (442, 41, 'Quận Hồng Bàng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (443, 41, 'Quận Lê Chân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (444, 41, 'Quận Ngô Quyền');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (445, 42, 'Huyện Quảng Điền');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (446, 42, 'Huyện Nam Đông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (447, 42, 'Huyện Phong Điền');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (448, 42, 'Huyện A Lưới');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (449, 42, 'Huyện Phú Lộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (450, 42, 'Huyện Phú Vang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (451, 42, 'Thị xã Hương Thủy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (452, 42, 'Thị xã Hương Trà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (453, 42, 'Thành phố Huế');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (454, 43, 'Huyện Tam Đảo');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (455, 43, 'Huyện Sông Lô');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (456, 43, 'Thành phố Phúc Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (457, 43, 'Huyện Tam Dương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (458, 43, 'Huyện Lập Thạch');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (459, 43, 'Huyện Yên Lạc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (460, 43, 'Huyện Vĩnh Tường');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (461, 43, 'Huyện Bình Xuyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (462, 43, 'Thành phố Vĩnh Yên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (463, 44, 'Huyện Vĩnh Thạnh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (464, 44, 'Huyện Thới Lai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (465, 44, 'Huyện Phong Điền');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (466, 44, 'Huyện Cờ Đỏ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (467, 44, 'Quận Thốt Nốt');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (468, 44, 'Quận Ô Môn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (469, 44, 'Quận Cái Răng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (470, 44, 'Quận Bình Thủy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (471, 44, 'Quận Ninh Kiều');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (472, 45, 'Huyện An Minh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (473, 45, 'Huyện Vĩnh Thuận');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (474, 45, 'Huyện U Minh Thượng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (475, 45, 'Huyện Giang Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (476, 45, 'Huyện Gò Quao');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (477, 45, 'Thành phố Phú Quốc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (478, 45, 'Huyện đảo Kiên Hải');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (479, 45, 'Thành phố Hà Tiên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (480, 45, 'Huyện Kiên Lương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (481, 45, 'Huyện An Biên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (482, 45, 'Huyện Giồng Riềng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (483, 45, 'Huyện Tân Hiệp');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (484, 45, 'Huyện Hòn Đất');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (485, 45, 'Huyện Châu Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (486, 45, 'Thành phố Rạch Giá');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (487, 46, 'Thị xã Vĩnh Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (488, 46, 'Huyện Thạnh Trị');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (489, 46, 'Huyện Mỹ Tú');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (490, 46, 'Huyện Long Phú');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (491, 46, 'Huyện Cù Lao Dung');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (492, 46, 'Thị xã Ngã Năm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (493, 46, 'Huyện Trần Đề');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (494, 46, 'Huyện Kế Sách');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (495, 46, 'Huyện Châu Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (496, 46, 'Huyện Mỹ Xuyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (497, 46, 'Thành phố Sóc Trăng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (498, 47, 'Huyện Châu Phú');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (499, 47, 'Huyện Chợ Mới');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (500, 47, 'Huyện Phú Tân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (501, 47, 'Thị Xã Tân Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (502, 47, 'Huyện An Phú');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (503, 47, 'Thành phố Châu Đốc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (504, 47, 'Huyện Tịnh Biên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (505, 47, 'Huyện Tri Tôn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (506, 47, 'Huyện Thoại Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (507, 47, 'Huyện Châu Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (508, 47, 'Thành phố Long Xuyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (509, 48, 'Huyện Hồng Ngự');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (510, 48, 'Huyện Hồng Ngự');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (511, 48, 'Huyện Châu Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (512, 48, 'Thành Phố Hồng Ngự');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (513, 48, 'Huyện Tháp Mười');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (514, 48, 'Huyện Thanh Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (515, 48, 'Huyện Tân Hồng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (516, 48, 'Huyện Tam Nông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (517, 48, 'Huyện Lấp Vò');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (518, 48, 'Huyện Lai Vung');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (519, 48, 'Huyện Cao Lãnh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (520, 48, 'Thành phố Sa Đéc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (521, 48, 'Thành phố Cao Lãnh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (522, 49, 'Huyện Vũng Liêm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (523, 49, 'Huyện Mang Thít');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (524, 49, 'Huyện Bình Tân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (525, 49, 'Thị xã Bình Minh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (526, 49, 'Huyện Trà Ôn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (527, 49, 'Huyện Tam Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (528, 49, 'Huyện Long Hồ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (529, 49, 'Thành phố Vĩnh Long');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (530, 50, 'Thị xã Duyên Hải');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (531, 50, 'Huyện Duyên Hải');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (532, 50, 'Huyện Cầu Kè');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (533, 50, 'Huyện Càng Long');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (534, 50, 'Huyện Trà Cú');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (535, 50, 'Huyện Tiểu Cần');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (536, 50, 'Huyện Châu Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (537, 50, 'Huyện Cầu Ngang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (538, 50, 'Thành phố Trà Vinh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (539, 51, 'Huyện Chợ Lách');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (540, 51, 'Huyện Thạnh Phú');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (541, 51, 'Huyện Mỏ Cày Nam');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (542, 51, 'Huyện Mỏ Cày Bắc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (543, 51, 'Huyện Giồng Trôm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (544, 51, 'Huyện Bình Đại');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (545, 51, 'Huyện Ba Tri');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (546, 51, 'Huyện Châu Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (547, 51, 'Thành phố Bến Tre');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (548, 52, 'Huyện Tân Phước');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (549, 52, 'Huyện Tân Phú Đông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (550, 52, 'Huyện Cai Lậy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (551, 52, 'Thị xã Gò Công');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (552, 52, 'Thị Xã Cai Lậy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (553, 52, 'Huyện Gò Công Tây');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (554, 52, 'Huyện Gò Công Đông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (555, 52, 'Huyện Cái Bè');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (556, 52, 'Huyện Chợ Gạo');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (557, 52, 'Huyện Châu Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (558, 52, 'Thành phố Mỹ Tho');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (559, 53, 'Thị xã Kiến Tường');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (560, 53, 'Huyện Vĩnh Hưng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (561, 53, 'Huyện Thạnh Hóa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (562, 53, 'Huyện Tân Thạnh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (563, 53, 'Huyện Tân Hưng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (564, 53, 'Huyện Mộc Hóa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (565, 53, 'Huyện Đức Huệ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (566, 53, 'Huyện Thủ Thừa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (567, 53, 'Huyện Tân Trụ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (568, 53, 'Huyện Đức Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (569, 53, 'Huyện Châu Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (570, 53, 'Huyện Cần Giuộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (571, 53, 'Huyện Cần Đước');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (572, 53, 'Huyện Bến Lức');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (573, 53, 'Thành phố Tân An');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (574, 54, 'Huyện M Đrắk');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (575, 54, 'Huyện Lắk');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (576, 54, 'Huyện Cư Kuin');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (577, 54, 'Huyện Krông Búk');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (578, 54, 'Huyện Ea Súp');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (579, 54, 'Huyện Krông Pắc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (580, 54, 'Huyện Ea Kar');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (581, 54, 'Huyện Krông Ana');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (582, 54, 'Huyện Krông Bông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (583, 54, 'Thị xã Buôn Hồ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (584, 54, 'Huyện Krông Năng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (585, 54, 'Huyện Ea H leo');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (586, 54, 'Huyện Cư M gar');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (587, 54, 'Huyện Buôn Ðôn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (588, 54, 'Thành phố Buôn Ma Thuột');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (589, 55, 'Huyện Di Linh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (590, 55, 'Huyện Cát Tiên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (591, 55, 'Huyện Đạ Tẻh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (592, 55, 'Huyện Đạ Huoai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (593, 55, 'Huyện Lâm Hà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (594, 55, 'Huyện Lạc Dương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (595, 55, 'Huyện Đam Rông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (596, 55, 'Huyện Bảo Lâm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (597, 55, 'Thành phố Bảo Lộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (598, 55, 'Huyện Đức Trọng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (599, 55, 'Huyện Đơn Dương');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (600, 55, 'Thành phố Đà Lạt');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (601, 56, 'Huyện Khánh Vĩnh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (602, 56, 'Huyện Khánh Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (603, 56, 'Huyện đảo Trường Sa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (604, 56, 'Thị xã Ninh Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (605, 56, 'Huyện Cam Lâm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (606, 56, 'Huyện Vạn Ninh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (607, 56, 'Huyện Diên Khánh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (608, 56, 'Thành phố Cam Ranh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (609, 56, 'Thành phố Nha Trang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (610, 57, 'Huyện Mang Yang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (611, 57, 'Huyện Krông Pa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (612, 57, 'Huyện Kông Chro');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (613, 57, 'Huyện Kbang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (614, 57, 'Huyện Đắk Pơ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (615, 57, 'Huyện Đắk Đoa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (616, 57, 'Huyện Chư Pưh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (617, 57, 'Huyện Chư Păh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (618, 57, 'Thị xã An Khê');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (619, 57, 'Huyện Ia Pa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (620, 57, 'Thị xã Ayun Pa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (621, 57, 'Huyện Phú Thiện');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (622, 57, 'Huyện Chư Sê');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (623, 57, 'Huyện Chư Prông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (624, 57, 'Huyện Đức Cơ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (625, 57, 'Huyện Ia Grai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (626, 57, 'Thành phố Pleiku');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (627, 58, 'Huyện đảo Côn Đảo');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (628, 58, 'Huyện Châu Đức');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (629, 58, 'Thị Xã Phú Mỹ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (630, 58, 'Huyện Xuyên Mộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (631, 58, 'Huyện Đất Đỏ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (632, 58, 'Huyện Long Điền');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (633, 58, 'TT Phú Mỹ - cũ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (634, 58, 'Thành phố Bà Rịa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (635, 58, 'Thành phố Vũng Tàu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (636, 59, 'Huyện Bắc Tân Uyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (637, 59, 'Huyện Bàu Bàng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (638, 59, 'Huyện Phú Giáo');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (639, 59, 'Huyện Dầu Tiếng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (640, 59, 'Thị xã Bến Cát');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (641, 59, 'Thành phố Tân Uyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (642, 59, 'Thành phố Thuận An');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (643, 59, 'Thành phố Dĩ An');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (644, 59, 'Thành phố Thủ Dầu Một');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (645, 60, 'Huyện Vĩnh Cửu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (646, 60, 'Huyện Nhơn Trạch');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (647, 60, 'Huyện Thống Nhất');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (648, 60, 'Huyện Xuân Lộc');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (649, 60, 'Huyện Cẩm Mỹ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (650, 60, 'Huyện Định Quán');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (651, 60, 'Huyện Long Thành');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (652, 60, 'Huyện Tân Phú');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (653, 60, 'Thành phố Long Khánh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (654, 60, 'Huyện Trảng Bom');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (655, 60, 'Thành phố Biên Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (656, 61, 'Huyện đảo Hoàng Sa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (657, 61, 'Huyện Hòa Vang');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (658, 61, 'Quận Cẩm Lệ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (659, 61, 'Quận Liên Chiểu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (660, 61, 'Quận Ngũ Hành Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (661, 61, 'Quận Sơn Trà');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (662, 61, 'Quận Thanh Khê');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (663, 61, 'Quận Hải Châu');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (664, 62, 'Thành Phố Thủ Đức');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (665, 62, 'Huyện Cần Giờ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (666, 62, 'Huyện Nhà Bè');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (667, 62, 'Huyện Bình Chánh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (668, 62, 'Quận Thủ Đức');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (669, 62, 'Quận Bình Thạnh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (670, 62, 'Quận Gò Vấp');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (671, 62, 'Huyện Củ Chi');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (672, 62, 'Huyện Hóc Môn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (673, 62, 'Quận Bình Tân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (674, 62, 'Quận Phú Nhuận');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (675, 62, 'Quận Tân Phú');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (676, 62, 'Quận Tân Bình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (677, 62, 'Quận 12');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (678, 62, 'Quận 11');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (679, 62, 'Quận 10');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (680, 62, 'Quận 9');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (681, 62, 'Quận 8');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (682, 62, 'Quận 7');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (683, 62, 'Quận 6');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (684, 62, 'Quận 5');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (685, 62, 'Quận 4');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (686, 62, 'Quận 3');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (687, 62, 'Quận 2');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (688, 62, 'Quận 1');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (689, 63, 'Quận Nam Từ Liêm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (690, 63, 'Huyện Thường Tín');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (691, 63, 'Huyện Phú Xuyên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (692, 63, 'Huyện Quốc Oai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (693, 63, 'Huyện Chương Mỹ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (694, 63, 'Huyện Ứng Hòa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (695, 63, 'Huyện Thanh Oai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (696, 63, 'Huyện Thạch Thất');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (697, 63, 'Huyện Phúc Thọ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (698, 63, 'Huyện Mỹ Đức');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (699, 63, 'Huyện Hoài Đức');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (700, 63, 'Huyện Đan Phượng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (701, 63, 'Huyện Ba Vì');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (702, 63, 'Thị xã Sơn Tây');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (703, 63, 'Huyện Thanh Trì');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (704, 63, 'Huyện Gia Lâm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (705, 63, 'Huyện Sóc Sơn');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (706, 63, 'Huyện Đông Anh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (707, 63, 'Huyện Mê Linh');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (708, 63, 'Quận Hà Đông');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (709, 63, 'Quận Thanh Xuân');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (710, 63, 'Quận Tây Hồ');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (711, 63, 'Quận Long Biên');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (712, 63, 'Quận Hoàng Mai');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (713, 63, 'Quận Hoàn Kiếm');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (714, 63, 'Quận Hai Bà Trưng');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (715, 63, 'Quận Đống Đa');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (716, 63, 'Quận Cầu Giấy');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (717, 63, 'Quận Ba Đình');
INSERT INTO `districts` (`id`, `province_id`, `name`) VALUES (718, 63, 'Quận Bắc Từ Liêm');
